trigger: none

pr:
  branches:
    include:
    - master
    - release/*.*
  paths:
    include:
    - '*'
    - docs/manpages/*
    exclude:
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

jobs:
#
# Checkout repository
#
- template: /eng/pipelines/common/checkout-job.yml
  parameters:
    paths:
    - subset: coreclr
      include:
      - src/libraries/System.Private.CoreLib/*
      exclude:
      - '*.md'
      - LICENSE.TXT
      - PATENTS.TXT
      - THIRD-PARTY-NOTICES.TXT
      - docs/*
      - src/installer/*
      - src/libraries/*
      - eng/pipelines/installer/*
      - eng/pipelines/libraries/*
    - subset: libraries
      exclude:
      - '*.md'
      - LICENSE.TXT
      - PATENTS.TXT
      - THIRD-PARTY-NOTICES.TXT
      - docs/*
      - src/installer/*
      - src/coreclr/*
      - eng/pipelines/coreclr/*
      - eng/pipelines/installer/*
    - subset: installer
      include:
      - docs/manpages/*
      exclude:
      - '*.md'
      - LICENSE.TXT
      - PATENTS.TXT
      - THIRD-PARTY-NOTICES.TXT
      - docs/*
      - src/coreclr/*
      - src/libraries/*
      - eng/pipelines/coreclr/*
      - eng/pipelines/libraries/*

- template: /eng/pipelines/common/platform-matrix-multijob.yml
  parameters:
    platforms:
    - OSX_x64
    - Linux_x64
    - Linux_arm
    - Windows_NT_x86
    - Windows_NT_x64
    - Windows_NT_arm
    - Windows_NT_arm64
    jobTemplates:

    #
    # Build CoreCLR
    #
    - jobTemplate: /eng/pipelines/coreclr/templates/build-job.yml
      buildConfig: checked
      jobParameters:
        testGroup: innerloop

    #
    # Build libraries using live CoreLib from CoreCLR
    #
    - jobTemplate: /eng/pipelines/libraries/build-job.yml
      buildConfig: Release
      jobParameters:
        isOfficialBuild: false
        liveCoreClrBuildConfig: checked

    #
    # Test builds using live libraries build
    #
    - jobTemplate: /eng/pipelines/coreclr/templates/build-test-job.yml
      buildConfig: checked
      jobParameters:
        testGroup: innerloop
        liveLibrariesBuildConfig: Release

    #
    # CoreCLR Test executions
    #
    - jobTemplate: /eng/pipelines/coreclr/templates/run-test-job.yml
      buildConfig: checked
      helixQueueGroup: pr
      helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
      jobParameters:
        testGroup: innerloop
        liveLibrariesBuildConfig: Release
        condition: false

    #
    # Libraries Test Build
    #
    - jobTemplate: /eng/pipelines/libraries/build-test-job.yml
      buildConfig: Release
      jobParameters:
        isOfficialBuild: false
        testScope: innerloop
        liveCoreClrBuildConfig: checked

    #
    # Libraries Test Execution
    #
    - jobTemplate: /eng/pipelines/libraries/run-test-job.yml
      buildConfig: Release
      helixQueueGroup: pr
      helixQueuesTemplate: /eng/pipelines/libraries/helix-queues-setup.yml
      jobParameters:
        isOfficialBuild: false
        isFullMatrix: false
        framework: netcoreapp
        testScope: innerloop
        liveCoreClrBuildConfig: checked
        dependsOnBuildConfiguration: Release
        condition: false

    #
    # Installer Build and Test
    #
    - jobTemplate: /eng/pipelines/installer/jobs/build-job.yml
      jobParameters:
        liveCoreClrBuildConfig: checked
        liveLibrariesBuildConfig: Release
