trigger: none

pr:
  branches:
    include:
    - master
    - release/*.*
  paths:
    include:
    - '*'
    - docs/manpages/*
    exclude:
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

variables:
- template: /eng/pipelines/common/variables.yml

# TODO: (Consolidation) Switch away from old signing/validation variables from former Core-Setup. https://github.com/dotnet/runtime/issues/1027
- name: TeamName
  value: dotnet-core-acquisition

# Set the target blob feed for package publish during official and validation builds.
- name: _DotNetArtifactsCategory
  value: .NETCore
- name: _DotNetValidationArtifactsCategory
  value: .NETCoreValidation

jobs:
#
# Checkout repository
#
- template: /eng/pipelines/common/checkout-job.yml
  parameters:
    paths:
    - subset: coreclr
      include:
      - src/libraries/System.Private.CoreLib/*
      exclude:
      - '*.md'
      - LICENSE.TXT
      - PATENTS.TXT
      - THIRD-PARTY-NOTICES.TXT
      - docs/*
      - src/installer/*
      - src/libraries/*
      - eng/pipelines/installer/*
      - eng/pipelines/libraries/*
    - subset: libraries
      exclude:
      - '*.md'
      - LICENSE.TXT
      - PATENTS.TXT
      - THIRD-PARTY-NOTICES.TXT
      - docs/*
      - src/installer/*
      - src/coreclr/*
      - eng/pipelines/coreclr/*
      - eng/pipelines/installer/*
    - subset: installer
      include:
      - docs/manpages/*
      exclude:
      - '*.md'
      - LICENSE.TXT
      - PATENTS.TXT
      - THIRD-PARTY-NOTICES.TXT
      - docs/*
      - src/coreclr/*
      - src/libraries/*
      - eng/pipelines/coreclr/*
      - eng/pipelines/libraries/*

- template: /eng/pipelines/common/platform-matrix-multijob.yml
  parameters:
    platforms:
    - OSX_x64
    - Linux_x64
    - Linux_arm
    - ${{ if eq(variables.isOfficialBuild, true) }}:
      - Linux_arm64
      - Linux_musl_x64
      - Linux_musl_arm64
    - Windows_NT_x86
    - Windows_NT_x64
    - Windows_NT_arm
    - Windows_NT_arm64
    jobTemplates:

    #
    # Build CoreCLR
    #
    - jobTemplate: /eng/pipelines/coreclr/templates/build-job.yml
      buildConfig: ${{ variables.coreClrBuildConfig }}
      jobParameters:
        isOfficialBuild: ${{ variables.isOfficialBuild }}
        testGroup: innerloop

    #
    # Build libraries using live CoreLib from CoreCLR
    #
    - jobTemplate: /eng/pipelines/libraries/build-job.yml
      buildConfig: ${{ variables.librariesBuildConfig }}
      jobParameters:
        isOfficialBuild: ${{ variables.isOfficialBuild }}
        liveCoreClrBuildConfig: ${{ variables.coreClrBuildConfig }}

    #
    # Installer Build and Test
    #
    - jobTemplate: /eng/pipelines/installer/jobs/build-job.yml
      buildConfig: ${{ variables.installerBuildConfig }}
      jobParameters:
        isOfficialBuild: ${{ variables.isOfficialBuild }}
        useOfficialAllConfigurations: ${{ variables.isOfficialBuild }}
        liveCoreClrBuildConfig: ${{ variables.coreClrBuildConfig }}
        liveLibrariesBuildConfig: ${{ variables.librariesBuildConfig }}

    - ${{ if eq(variables.isOfficialBuild, true) }}:
      #
      # Test builds using live libraries build
      #
      - jobTemplate: /eng/pipelines/coreclr/templates/build-test-job.yml
        buildConfig: ${{ variables.coreClrBuildConfig }}
        jobParameters:
          testGroup: innerloop
          liveLibrariesBuildConfig: ${{ variables.librariesBuildConfig }}

      #
      # CoreCLR Test executions
      #
      - jobTemplate: /eng/pipelines/coreclr/templates/run-test-job.yml
        buildConfig: ${{ variables.coreClrBuildConfig }}
        helixQueueGroup: pr
        helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
        jobParameters:
          testGroup: innerloop
          liveLibrariesBuildConfig: ${{ variables.librariesBuildConfig }}
          condition: false

      #
      # Libraries Test Build
      #
      - jobTemplate: /eng/pipelines/libraries/build-test-job.yml
        buildConfig: ${{ variables.librariesBuildConfig }}
        jobParameters:
          isOfficialBuild: false
          testScope: innerloop
          liveCoreClrBuildConfig: ${{ variables.coreClrBuildConfig }}

      #
      # Libraries Test Execution
      #
      - jobTemplate: /eng/pipelines/libraries/run-test-job.yml
        buildConfig: ${{ variables.librariesBuildConfig }}
        helixQueueGroup: pr
        helixQueuesTemplate: /eng/pipelines/libraries/helix-queues-setup.yml
        jobParameters:
          isOfficialBuild: false
          isFullMatrix: false
          framework: netcoreapp
          testScope: innerloop
          liveCoreClrBuildConfig: ${{ variables.coreClrBuildConfig }}
          dependsOnBuildConfiguration: ${{ variables.librariesBuildConfig }}
          condition: false

- ${{ if eq(variables.isOfficialBuild, true) }}:
  - template: /eng/pipelines/official/stages/publish.yml
